zip: gspread_credentials.json rackspace_automation.py
	zip -d rackspace_automation.zip gspread_credentials.json \
	rackspace_automation.py \
	~/.virtualenvs/rackspace-automation-min/lib/python2.7/site-packages/* -r